### ISSUE TITLE
Extra parameter in vkb::SwapchainBuilder

### ISSUE THREAD

**Issue by Eearslya** [vblanco20-1/vulkan-guide#10]
Chapter 1, "Vulkan Initialization Code", under "Setting up the swapchain" includes the following line of example code:

```cpp
vkb::SwapchainBuilder swapchainBuilder{_chosenGPU,_device,_surface,_graphicsQueueFamily };
```

`_graphicsQueueFamily` has not been created at this point, nor can I see any constructor for `vkb::SwapchainBuilder` that takes a queue family as a parameter.

**Comment by cdgiessen** [comment]
Ack this is an oversight on my part. Just put 0 instead of _graphicsQueueFamily  and it should work.

This is because the swapchain builder *needs* to know what the graphics queue family index is, but we don't want to pollute the VulkanEngine with a bunch of vk-bootstrap types (since it bloats headers and isn't needed anywhere else). Sometimes 'simple' interfaces over complex object initialization can leak, and this is one of those times.

**Comment by Eearslya** [comment]
> This is because the swapchain builder needs to know what the graphics queue family index is

Does it, though? I took a peek into VkBootstrap and there doesn't seem to be any constructor that even takes 4 parameters at all...

![image](https://user-images.githubusercontent.com/2270586/97202795-4d445800-1771-11eb-92cc-2f0b1eeac72b.png)

**Comment by cdgiessen** [comment]
During most of the writing of this tutorial, the vk-bootstrap in third_party was an older version. Last week I updated the repo to use the newer version (which fixed bugs and other good stuff). The code you are looking at is the older version.

The thing is that the swapchain *needs* the graphics queue family index, so if you want to use the 'raw VK handle' constructor for the swapchain (so you don't have to hold the vkb::Device object), you have to pass in the queue family index manually. The other constructors know how to get it.

**Comment by cdgiessen** [comment]
I'm looking at the `all-chapters` branch of the repo and I'm seeing the newer version.
https://github.com/vblanco20-1/vulkan-guide/blob/fee5dbddf0c9f5959ca75902697cc60f1761961c/third_party/vkbootstrap/VkBootstrap.cpp#L1540

And I was pretty sure I updated the tutorial code to match the latest vk-bootstrap commit
https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.h

**Comment by Eearslya** [comment]
Oh, interesting. I'm currently following through from the `starting-point` branch. So maybe it's that branch that needs an update to VkBootstrap?

**Comment by cdgiessen** [comment]
Ah, that would explain everything. My bad, I didn't see that branch when I was updating the library. Seems I need to make a PR pronto.

**Comment by Eearslya** [comment]
Glad that's cleared up! I'm keeping track of a couple other minor errata while I go through (only one other so far), but thus far it's a great guide. It's exactly the step-up from vulkan-tutorial that I've been wanting for so long. :smile:

**Comment by vblanco20-1** [comment]
Thanks for reporting the issue. I merged the PR that updates the thing, so it should be fine now
