### ISSUE TITLE
[GLTF Loading]

### ISSUE THREAD

**Issue by matt328** [vblanco20-1/vulkan-guide#100]
In case anyone else gets stuck on this, with newer versions of fastgltf (I am using 7.0.0), the functions you pass to `fastgltf::visitor`, the signatures seem to have changed slightly, causing ... odd behavior.  Specifically, the branch that takes a `fastgltf::sources::Vector&` should be `const fastgltf::sources::Array&`. Probably an update to fastgltf since the time of writing. According to their docs, `sources::Vector` is only used for writing out gltf files, and reading should always use `sources::Array`.  Also don't forget to mark it as a const reference or else it will still match, but the bytes will be filled with junk, and you'll bang your head for 3 days reevaluating your entire asset loading system. Or maybe that was just me.

**Comment by vblanco20-1** [comment]
Fastgltf and other libraries the tutorial depends on are vendored with the repo in starting-point-2. I recommend people to go with that and only later attempt to update the version of the libraries so that you can follow the tutorial smoothly. The library versions will be upgraded as the tutorial sees improvements and updates.

**Comment by spnda** [comment]
> Also don't forget to mark it as a const reference or else it will still match, but the bytes will be filled with junk

That sounds like a bug in my Array implementation... weird. Did you use a lambda with a copy? So `[&](sources::Array array)`? Then my copy constructor might be broken. Do you remember more precisely what your setup looked like when you encountered this issue, specifically? If you don't mind you could open an issue on my repository.
