### ISSUE TITLE
Setting up ImGui section of chapter 2

### ISSUE THREAD

**Issue by FeralPug** [vblanco20-1/vulkan-guide#101]
I was having an issue with ImGui looking all glitched out. What fixed it for me was noticing and changing the image layout in the draw_imgui method.

**In the chapter and the code on github the for chapter 2, the draw_imgui() is as follows:**

void VulkanEngine::draw_imgui(VkCommandBuffer cmd, VkImageView targetImageView)
{
	VkRenderingAttachmentInfo colorAttachment = vkinit::attachment_info(targetImageView, nullptr, VK_IMAGE_LAYOUT_GENERAL);
	VkRenderingInfo renderInfo = vkinit::rendering_info(_swapchainExtent, &colorAttachment, nullptr);

	vkCmdBeginRendering(cmd, &renderInfo);

	ImGui_ImplVulkan_RenderDrawData(ImGui::GetDrawData(), cmd);

	vkCmdEndRendering(cmd);
}

**but the target image we send in is not set as VK_IMAGE_LAYOUT_GENERAL but as VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL (see snippet from draw function)**

// set swapchain image layout to Attachment Optimal so we can draw it
vkutil::transition_image(cmd, _swapchainImages[swapchainImageIndex], VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);

//draw imgui into the swapchain image
draw_imgui(cmd,  _swapchainImageViews[swapchainImageIndex]);

**So the actual draw_imgui method should be as follows**

void VulkanEngine::draw_imgui(VkCommandBuffer cmd, VkImageView targetImageView) {
    VkRenderingAttachmentInfo colorAttachment = vkinit::attachment_info(targetImageView, nullptr, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);
    VkRenderingInfo renderInfo = vkinit::rendering_info(_swapchainExtent, &colorAttachment, nullptr);

    vkCmdBeginRendering(cmd, &renderInfo);

    ImGui_ImplVulkan_RenderDrawData(ImGui::GetDrawData(), cmd);

    vkCmdEndRendering(cmd);
}

**Comment by tom-leys** [comment]
It appears this is fixed now and this issue should be closed.
