### ISSUE TITLE
Starting point 2 has outdated imgui_impl_vulkan.h

### ISSUE THREAD

**Issue by DinDotDout** [vblanco20-1/vulkan-guide#112]
While all-chapters-2 has the last imgui version as per the vkguide, starting-point-2 still uses the older version, and thus cannot initialize the ImGui_ImplVulkan_InitInfo struct as the guide says.

**Comment by vblanco20-1** [comment]
its known, will be fixed once i refresh a couple tutorial things

**Comment by DinDotDout** [comment]
Awesome, thanks for the hard work

**Comment by vblanco20-1** [comment]
its fixed now
