### ISSUE TITLE
ETA on future chapters

### ISSUE THREAD

**Issue by h4chi** [vblanco20-1/vulkan-guide#115]
With reference to the Deprecation Warning on: https://vkguide.dev/docs/gpudriven/gpu_driven_engines/

Is there a timeline for the future chapters/planned updates and would you be able to share those?

Thanks for the great resource!

**Comment by vblanco20-1** [comment]
Im working on a custom engine for a project right now, but after this reaches prototype/vertical slice level, i will probably bring back some tech to vkguide for chapters 6 and 7. The plan is that 6 and 7 will continue the development of the engine by adding lighting (with shadows) and draw indirect paths.
