### ISSUE TITLE
Chapter 1 Errata

### ISSUE THREAD

**Issue by Eearslya** [vblanco20-1/vulkan-guide#12]
Just finished going through chapter 1! Great stuff you guys have here, and I'm excited to see the rest.

I did notice just two minor nitpicks within the example code while going through:

Chapter 1 - Setting up renderpass code
  `init_commands` is shown before it is created. Looks like the commands and renderpass sections may have traded places at one point?

Chapter 1 - Setting up Vulkan commands
  `vkinit::command_pool_create_info` should have `VkCommandPoolCreateFlags` parameter instead of `VkCommandPoolResetFlags`

**Comment by vblanco20-1** [comment]
Good find. It was indeed swapped. Ive fixed the issue
