### ISSUE TITLE
vk_initializers.h instead of vk_types.h in chapter 0, Code Walkthrough

### ISSUE THREAD

**Issue by Tetane** [vblanco20-1/vulkan-guide#18]
Hi, I think there is a small mistake in `chapter-0/code_walkthrough.md`.

> ...
> vk_initializers.h holds this
> 
> ```cpp
> #pragma once
> #include <vulkan/vulkan.h>
> ```
> ...

It should be "vk_types.h holds this".

**Comment by vblanco20-1** [comment]
Fixed
