### ISSUE TITLE
Add a content license

### ISSUE THREAD

**Issue by Calinou** [vblanco20-1/vulkan-guide#20]
The tutorial text itself (and code samples) currently doesn't seem to be under any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

I would recommend [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) for text and [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) for code samples.

**Comment by vblanco20-1** [comment]
Entire thing (code and text) is MIT and configured as such in github
