### ISSUE TITLE
Cleanup Synchronization Structures

### ISSUE THREAD

**Issue by itmuckel** [vblanco20-1/vulkan-guide#22]
Hi! Great tutorial!
I just finished chapter 1 and got errors that
1. the synchronization structures were still in use.
1. the synchronization structures weren't destructed.

I'd suggest to add this cleanup code at the end of chapter 1:

```cpp
vkDeviceWaitIdle(_device);

vkDestroySemaphore(_device, _renderSemaphore, nullptr);
vkDestroySemaphore(_device, _presentSemaphore, nullptr);
vkDestroyFence(_device, _renderFence, nullptr);
```

Other than that great, thank you for putting this together!

**Comment by vblanco20-1** [comment]
All chapters now use vkDeviceWaitIdle in the code, and ill update the text part soon. Should help with all that
