### ISSUE TITLE
Chapter 4 validation errors

### ISSUE THREAD

**Issue by warriormaster12** [vblanco20-1/vulkan-guide#29]
There are tons of validations errors related to command buffer being in use when quitting the application. 

[ERROR: General]
/usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
[ERROR: General]
/usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
The gpu has a minimum buffer alignement of 256
WARN: Material file [ monkey_smooth.mtl ] not found in a path : 
Failed to load material file(s). Use default material.
material [ 'None' ] not found in .mtl

[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x1f000000001f, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkBuffer 0x1f000000001f[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x1e000000001e, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkBuffer 0x1e000000001e[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x220000000022, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkBuffer 0x220000000022[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x230000000023, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkBuffer 0x230000000023[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x1c000000001c, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkBuffer 0x1c000000001c[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xb000000000b, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkDeviceMemory 0xb000000000b[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
[ERROR: Validation]
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x55f937376068, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x1d000000001d, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x55f937376068[], VkDeviceMemory 0x1d000000001d[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://vulkan.lunarg.com/doc/view/1.2.162.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyDevice-device-00378)
VulkanEngine: /media/Programs/Programming/C++/VulkanEngine/Engine/Source/Vulkan/../third-party/Vma/vk_mem_alloc.h:12318: void VmaDeviceMemoryBlock::Destroy(VmaAllocator): Assertion `m_pMetadata->IsEmpty() && "Some allocations were not freed before destruction of this memory block!"' failed.
Aborted (core dumped)

Also there should be probably a mention, how to cleanup descriptor sets .
Added this to the end of init_descriptors function 
`_mainDeletionQueue.push_function([=]() {
		vkDestroyDescriptorSetLayout(_device, _globalSetLayout, nullptr);
		vkDestroyDescriptorSetLayout(_device, _objectSetLayout, nullptr);
		vkDestroyDescriptorPool(_device, _descriptorPool, nullptr);
	});
`

**Comment by warriormaster12** [comment]
managed to fix some of the errors 
https://github.com/warriormaster12/VulkanEngine/commit/307ec1ef18433a0e52dd05762697434d99c1ac46

**Comment by warriormaster12** [comment]
Another update. Managed to fix them all but I still think that there should be a mention of how to cleanup like in vulkan-tutorial. 
https://github.com/warriormaster12/VulkanEngine/commit/9a59baec98083a29888056d28d738752e28cd376

**Comment by vblanco20-1** [comment]
All of this is now addresed in the main repo. Ive tweaked the code to clean everything correctly on exit for allchapters
