### ISSUE TITLE
Cannot compile asset-baker

### ISSUE THREAD

**Issue by itmuckel** [vblanco20-1/vulkan-guide#30]
Hi!
The last week I tried to compile the asset-baker, but I can't make it work.
It can't find stb_image and nvtt, but I don't know why. I installed both via vcpkg in many different versions, tried release builds, static builds etc. None worked.

I get many many errors like these:
```
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_load_from_memory
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_load
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_load_16_from_memory
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_image_free
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_is_16_bit_from_memory
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_write_png_to_func
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_write_bmp_to_func
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol stbi_write_jpg_to_func
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\asset_main.cpp.obj : error LNK2001: unresolved external symbol "bool __cdecl tinyobj::LoadObj(struct tinyobj::attrib_t *,class std::vector<struct tinyobj::shape_t,class std::allocator<struct tinyobj::shape_t> > *,class std::vector<struct tinyobj::_material_t,class std::allocator<struct tinyobj::_material_t> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,char const *,char const *,bool,bool)" (?LoadObj@tinyobj@@YA_NPEAUattrib_t@1@PEAV?$vector@Ushape_t@tinyobj@@V?$allocator@Ushape_t@tinyobj@@@std@@@std@@PEAV?$vector@U_material_t@tinyobj@@V?$allocator@U_material_t@tinyobj@@@std@@@4@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@3PEBD4_N5@Z)
D:\Code\cpp\vulkan-guide\out\build\x64-Debug (default)\nvtt.lib(CompressionOptions.obj) : error LNK2001: unresolved external symbol "int __cdecl nvAbort(char const *,char const *,int,char const *,char const *,...)" (?nvAbort@@YAHPEBD0H00ZZ)
```
... and many more nvtt.lib unresolved external symbol errors.

I don't know what I'm doing wrong. Here is my repo: https://github.com/itmuckel/vulkan-guide

**Comment by vblanco20-1** [comment]
Hi @itmuckel , the asset-baker is mostly meant as an example, and its used in the "engine" branch that its a lot more advanced and quite underexplained. I dont recomend trying to get it to work when you are just going through the chapters, as its unnecesary for the main 5 chapters.
If you really want to get the "engine" branch running you will need it to compile some basic GLTF Assets exported from blender to render them. But to do that it wont be so easy. asset-baker requires Assimp (has to be compiled manually), nvidia texture tools (has to be compiled manually), and other libs that are easier to get running as they are header only. The cmake file in the branch is the correct one, but the built libraries for nvidia texture tools and assimp arent in the git repo. You will have to build them yourself somehow. For now use the cmakelists at that branch as a comparaison, pay attention to the cmake in the third-party folder as its where it creates the lib targets.

**Comment by itmuckel** [comment]
I already finished the main 5 chapters and wanted to continue on GPU-driven rendering, but it said that there have been some modifications to the code. Then I tried to do the extra chapters and  when I saw that the assetlib in the engine branch that I was using as comparison was much more advanced than what was explained in the corresponding page, I thought I'd just take everything from the engine directory (regarding asset-baker and assetlib).

I'm using vcpkg, so I didn't have to compile assimp or anything else. 

Hmmm... Is there any "starting point" for the GPU-driven rendering part? I'd really like to learn more about bindless rendering!

**Comment by vblanco20-1** [comment]
@itmuckel  the gpu driven chapter is mostly high level explanations of how the codebase works. You can use that as an example, but it isnt handholded like the main chapters are. I recomend you try to implement the stuff yourself, as the specifics of the indirect drawing will be dependant on the game you want to make. You can start by having it write the indirect buffer on the cpu side with 1 draw command per object. That should be relatively doable. You can also look at the draw indirect samples in the Sasha willems vulkan samples repo

**Comment by itmuckel** [comment]
Thank you, I'll do that!
