### ISSUE TITLE
Incorrect sync in vkQueuePresent

### ISSUE THREAD

**Issue by HildarTheDorf** [vblanco20-1/vulkan-guide#31]
The semaphore passed to vkQueuePresent should be per-image-index not per-frame-index.

The semaphore passed to vkQueuePresent can't be submitted for signalling again until it's retired. As there's no signal semaphore/fence parameter to vkQueuePresent, the only way to know it's retired is if vkAcquireNextImage returns the same imageIndex (and has fully completed, i.e. it has signaled the semaphore/fence passed to it).

The current setup (per-frame) works if presentation engines return images in order (and the swapchain has the same or more images than frames-in-flight), but this is not contractually guaranteed and out-of-order acquires is explicitly allowed by the spec. A 3 image swapchain could for example hand out images in the order 012121212121212 etc., and the semaphore used for the first present call would be rendered unusable.

**Comment by abhineet99** [comment]
+1, faced this during swapchain recreation (was adding code inspired from Sascha Willems)

**Comment by vblanco20-1** [comment]
fixed in vkguide 2
