### ISSUE TITLE
Incorrect statement on line 32 of master/docs/chapter-4/descriptors.md

### ISSUE THREAD

**Issue by SirFirelordX** [vblanco20-1/vulkan-guide#37]
On the specified line, the tutorial states that enabling the VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT flag when creating a descriptor pool disallows freeing individual descriptor sets, however, according to the spec, this flag enables this functionality instead of disallowing it
![image](https://user-images.githubusercontent.com/56412989/120087752-73333180-c09f-11eb-90af-b84be887250a.png)
![image](https://user-images.githubusercontent.com/56412989/120087756-7af2d600-c09f-11eb-97c3-d0289a3dd0d2.png)

**Comment by vblanco20-1** [comment]
Ill fix it
