### ISSUE TITLE
Trying to compile Engine branch but get errors

### ISSUE THREAD

**Issue by Gunnl** [vblanco20-1/vulkan-guide#49]
```
third-party/imgui/imgui_impl_sdl.cpp:50:10: fatal error: SDL.h: No such file or directory
   50 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [third-party/CMakeFiles/imgui.dir/build.make:160: third-party/CMakeFiles/imgui.dir/imgui/imgui_impl_sdl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:392: third-party/CMakeFiles/imgui.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by Gunnl** [comment]
not sure if this it the most elegant solution however, to circumvent this I have added 

find_package(SDL2 REQUIRED)
include_directories(${SDL2_INCLUDE_DIRS})

to the CMakeLists.txt root file.

**Comment by Gunnl** [comment]
This however results in another error:
```
make[2]: *** No rule to make target '../libs/Release/nvtt.lib', needed by 'baker'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:446: asset-baker/CMakeFiles/baker.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by Gunnl** [comment]
Also, .. forgot to mention .. there is a compile error:
```
ssetlib/asset_loader.cpp:70:13: error: ‘strcmp’ was not declared in this scope
   70 |         if (strcmp(f, "LZ4") == 0)
```
that you can easily fix by including the required header <cstring>

**Comment by tysonmalchow** [comment]
i'm hitting the same issue

**Comment by vblanco20-1** [comment]
@Gunnl , @tysonmalchow  what platform are you using it from? The code was checked for compile in visual studio, but maybe the problem is in clang or gcc.

**Comment by Gunnl** [comment]
Yeah... i found it that later... I am running linux (arch linux) ... I decided to drop the comment anyway, perhaps will help someone in future...

**Comment by CMDR-Piboy314** [comment]
if you do not wish to use include_directories, you can also simply do `SDL2/sdl.h` instead

**Comment by Ribosome2** [comment]
> 

I got the same error ,can't run the engine branch,how did you solve it ?

**Comment by dsvua** [comment]
Unfortunately, I have same error as OP and I am trying to use VSCode on Widows 11. I did not install SDL separately, but I see it is installed with Vulkan. Do I need to do anything extra to install SDL?

**Comment by dsvua** [comment]
For anyone having similar issue with VSCode and SDL, those are steps to make it working:
1. Download `SDL-devel-x.xx.x-VC` file and extract it.
2. Copy `..cmake\sdl2-config.cmake` to root.
3. Update line `set(sdl2_DIR "SDL_PATH" CACHE FILEPATH "Path to SDL2")` in `third_party\CMakeLists.txt` in `vulkan-guide`.
Now you should be able to compile.

For example:
1. I downloaded SDL2-devel-2.30.1-VC version
2. Copied `sdl2-config.cmake` from `C:\Users\some_user\Downloads\SDL2-devel-2.30.1-VC\SDL2-2.30.1\cmake` to `C:\Users\some_user\Downloads\SDL2-devel-2.30.1-VC\SDL2-2.30.1`
3. Update line `set(sdl2_DIR "SDL_PATH" CACHE FILEPATH "Path to SDL2")` in `third_party\CMakeLists.txt` in `vulkan-guide` to look like `set(sdl2_DIR "C:/Users/some_user/Downloads/SDL2-devel-2.30.1-VC/SDL2-2.30.1" CACHE PATH "Path to SDL2")`

**Comment by vblanco20-1** [comment]
@dsvua  the engine branch is heavily outdated, i dont recomend trying to make it run, and its missing the assets. I havent removed it only because it contains the shaders for the gpu-driven chapter

**Comment by dsvua** [comment]
Thank you. I switched to `all-chapters-1.3-wip` and so far so good. No need for manual changes as it already have SDL in third-party folder.
