### ISSUE TITLE
Optional chapter that explains how to initialize that Vulkan boilerplate the “manual” way

### ISSUE THREAD

**Issue by zheng95z** [vblanco20-1/vulkan-guide#70]
The introduction section said that
> [Vk Bootstrap](https://github.com/charles-lunarg/vk-bootstrap/blob/master/src/VkBootstrap.cpp) Abstracts a big amount of boilerplate that Vulkan has when setting up. Most of that code is written once and never touched again, so we will skip most of it using this library. This library simplifies instance creation, swapchain creation, and extension loading. It will be removed from the project eventually in an optional chapter that explains how to initialize that Vulkan boilerplate the “manual” way.

I now want to remove vk-bootstrap library, and I'm wondering where can I find such an "optional chapter" concerning initializing the Vulkan boilerplate the manual way?

BTW, a great tutorial!

**Comment by vblanco20-1** [comment]
I dont think such a chapter is necesary as vulkan-tutorial already spends half of the tutorial explaining that code.
