### ISSUE TITLE
Code for the GPU-driven chapter and how to build it

### ISSUE THREAD

**Issue by Nolram12345** [vblanco20-1/vulkan-guide#90]
Hi there! I'm currently studying GPU-driven rendering for educational purposes, and I was looking through the GPU-driven chapter of vkguide, and wanted to study the source code - however, it doesn't seem that it is available in this repository?

**Comment by Speak2Erase** [comment]
It's under the engine branch

**Comment by Nolram12345** [comment]
Thank you!

**Comment by Nolram12345** [comment]
So I checked it out, tried for about 3 hours to compile it - no chance. It's a bloody mess.
@vblanco20-1 Any considerations on cleaning up the engine branch and/or how to build it? Or perhaps including some of the GPU-driven chapter in the main branch in a cleaner version?

**Comment by vblanco20-1** [comment]
vkguide 2 is coming some time and all that stuff will be rewritten

**Comment by Nolram12345** [comment]
Awesome! Can't wait to see it. Any ETA? How far along is it?

**Comment by vblanco20-1** [comment]
@Nolram12345  vkguide 2 is now released, but the GPU driven chapter v2 will take a bit more
