### ISSUE TITLE
Calculation of the flash value using abs, instead of std::abs or fabs.

### ISSUE THREAD

**Issue by Julian-Mej** [vblanco20-1/vulkan-guide#97]
`float flash = abs(sin(_frameNumber / 120.f));`
This line is causing a problem when running the code from the "Mainloop Code" chapter. The `abs` function outside the `std`-namespace casts the parameter to an int, which leads to `flash` always being zero, making the screen always appear black. I suggest replacing it with `std::abs` or `fabs. This StackOverflow answer explains why that makes a difference: [https://stackoverflow.com/a/3118188](https://stackoverflow.com/a/3118188).

**Comment by vblanco20-1** [comment]
Fixing it on next update
