### ISSUE TITLE
Backwards Colors

### ISSUE THREAD

**Issue by Enator18** [vblanco20-1/vulkan-guide#98]
The second section of chapter 4 titled "Textures" has a part where it creates some basic textures procedurally. The colors are written in the reverse byte order that they should be, causing the "black" to show up as red, the "grey" to show up as pink, and the "magenta" to show up as yellow.

**Comment by Acclution** [comment]
I had the same problem and I fixed it for me with glm:
```
uint32_t white = glm::packUnorm4x8(glm::vec4(1, 1, 1, 1));
uint32_t black = glm::packUnorm4x8(glm::vec4(0, 0, 0, 0));
uint32_t gray = glm::packUnorm4x8(glm::vec4(0.66f, 0.66f, 0.66f, 1));
uint32_t magenta = glm::packUnorm4x8(glm::vec4(1, 0, 1, 1));
```

**Comment by vblanco20-1** [comment]
Fixing it on next update
